# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1014, 867)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.PacketList = QtGui.QTableWidget(self.centralwidget)
        self.PacketList.setGeometry(QtCore.QRect(20, 50, 971, 271))
        self.PacketList.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.PacketList.setIconSize(QtCore.QSize(0, 0))
        self.PacketList.setObjectName(_fromUtf8("PacketList"))
        self.PacketList.setColumnCount(5)
        self.PacketList.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.PacketList.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.PacketList.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.PacketList.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.PacketList.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.PacketList.setHorizontalHeaderItem(4, item)
        self.PacketList.horizontalHeader().setVisible(True)
        self.PacketList.horizontalHeader().setCascadingSectionResizes(False)
        self.PacketList.horizontalHeader().setDefaultSectionSize(100)
        self.PacketList.horizontalHeader().setHighlightSections(True)
        self.PacketList.horizontalHeader().setMinimumSectionSize(56)
        self.PacketList.horizontalHeader().setSortIndicatorShown(False)
        self.PacketList.horizontalHeader().setStretchLastSection(True)
        self.PacketList.verticalHeader().setVisible(True)
        self.PacketList.verticalHeader().setCascadingSectionResizes(False)
        self.PacketList.verticalHeader().setDefaultSectionSize(30)
        self.PacketList.verticalHeader().setSortIndicatorShown(False)
        self.PacketList.verticalHeader().setStretchLastSection(False)
        self.PacketInfo = QtGui.QTabWidget(self.centralwidget)
        self.PacketInfo.setGeometry(QtCore.QRect(20, 340, 531, 451))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nimbus Roman No9 L"))
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.PacketInfo.setFont(font)
        self.PacketInfo.setElideMode(QtCore.Qt.ElideRight)
        self.PacketInfo.setObjectName(_fromUtf8("PacketInfo"))
        self.Ethernet = QtGui.QWidget()
        self.Ethernet.setObjectName(_fromUtf8("Ethernet"))
        self.Ethernet_text = QtGui.QTableWidget(self.Ethernet)
        self.Ethernet_text.setGeometry(QtCore.QRect(0, 0, 531, 421))
        self.Ethernet_text.setStyleSheet(_fromUtf8(""))
        self.Ethernet_text.setObjectName(_fromUtf8("Ethernet_text"))
        self.Ethernet_text.setColumnCount(0)
        self.Ethernet_text.setRowCount(0)
        self.Ethernet_text.verticalHeader().setVisible(False)
        self.Ethernet_text.verticalHeader().setHighlightSections(True)
        self.PacketInfo.addTab(self.Ethernet, _fromUtf8(""))
        self.ip = QtGui.QWidget()
        self.ip.setObjectName(_fromUtf8("ip"))
        self.ip_text = QtGui.QTableWidget(self.ip)
        self.ip_text.setGeometry(QtCore.QRect(0, 0, 531, 421))
        self.ip_text.setObjectName(_fromUtf8("ip_text"))
        self.ip_text.setColumnCount(0)
        self.ip_text.setRowCount(0)
        self.ip_text.verticalHeader().setVisible(False)
        self.PacketInfo.addTab(self.ip, _fromUtf8(""))
        self.more = QtGui.QWidget()
        self.more.setObjectName(_fromUtf8("more"))
        self.more_text = QtGui.QTableWidget(self.more)
        self.more_text.setGeometry(QtCore.QRect(0, 0, 531, 421))
        self.more_text.setObjectName(_fromUtf8("more_text"))
        self.more_text.setColumnCount(0)
        self.more_text.setRowCount(0)
        self.more_text.verticalHeader().setVisible(False)
        self.PacketInfo.addTab(self.more, _fromUtf8(""))
        self.RawDataHex = QtGui.QTextEdit(self.centralwidget)
        self.RawDataHex.setGeometry(QtCore.QRect(570, 370, 421, 191))
        self.RawDataHex.setObjectName(_fromUtf8("RawDataHex"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(570, 340, 131, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nimbus Roman No9 L"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.RawDataStr = QtGui.QTextEdit(self.centralwidget)
        self.RawDataStr.setGeometry(QtCore.QRect(570, 600, 421, 191))
        self.RawDataStr.setObjectName(_fromUtf8("RawDataStr"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(570, 570, 151, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nimbus Roman No9 L"))
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 971, 41))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.StartButton = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nimbus Roman No9 L"))
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.StartButton.setFont(font)
        self.StartButton.setStyleSheet(_fromUtf8(""))
        self.StartButton.setObjectName(_fromUtf8("StartButton"))
        self.horizontalLayout.addWidget(self.StartButton)
        self.StopButton = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nimbus Roman No9 L"))
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.StopButton.setFont(font)
        self.StopButton.setObjectName(_fromUtf8("StopButton"))
        self.horizontalLayout.addWidget(self.StopButton)
        self.pushButton_4 = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nimbus Roman No9 L"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.pushButton_7 = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nimbus Roman No9 L"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.horizontalLayout.addWidget(self.pushButton_7)
        self.pushButton_5 = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nimbus Roman No9 L"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.horizontalLayout.addWidget(self.pushButton_5)
        self.pushButton_6 = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nimbus Roman No9 L"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.horizontalLayout.addWidget(self.pushButton_6)
        self.pushButton = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nimbus Roman No9 L"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nimbus Roman No9 L"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nimbus Roman No9 L"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_10 = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nimbus Roman No9 L"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.horizontalLayout.addWidget(self.pushButton_10)
        self.pushButton_8 = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nimbus Roman No9 L"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.horizontalLayout.addWidget(self.pushButton_8)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1014, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu6516 = QtGui.QMenu(self.menubar)
        self.menu6516.setObjectName(_fromUtf8("menu6516"))
        self.menuSave = QtGui.QMenu(self.menu6516)
        self.menuSave.setObjectName(_fromUtf8("menuSave"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuSniff = QtGui.QMenu(self.menubar)
        self.menuSniff.setObjectName(_fromUtf8("menuSniff"))
        self.menuFilter = QtGui.QMenu(self.menubar)
        self.menuFilter.setObjectName(_fromUtf8("menuFilter"))
        self.menuRecombine_2 = QtGui.QMenu(self.menuFilter)
        self.menuRecombine_2.setObjectName(_fromUtf8("menuRecombine_2"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave_as_pcap = QtGui.QAction(MainWindow)
        self.actionSave_as_pcap.setObjectName(_fromUtf8("actionSave_as_pcap"))
        self.actionSave_as_txt = QtGui.QAction(MainWindow)
        self.actionSave_as_txt.setObjectName(_fromUtf8("actionSave_as_txt"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionChange_Interface = QtGui.QAction(MainWindow)
        self.actionChange_Interface.setObjectName(_fromUtf8("actionChange_Interface"))
        self.actionBegin = QtGui.QAction(MainWindow)
        self.actionBegin.setObjectName(_fromUtf8("actionBegin"))
        self.actionStop = QtGui.QAction(MainWindow)
        self.actionStop.setObjectName(_fromUtf8("actionStop"))
        self.actionClear = QtGui.QAction(MainWindow)
        self.actionClear.setObjectName(_fromUtf8("actionClear"))
        self.actionClear_History = QtGui.QAction(MainWindow)
        self.actionClear_History.setObjectName(_fromUtf8("actionClear_History"))
        self.actionFilter = QtGui.QAction(MainWindow)
        self.actionFilter.setObjectName(_fromUtf8("actionFilter"))
        self.actionSearch = QtGui.QAction(MainWindow)
        self.actionSearch.setObjectName(_fromUtf8("actionSearch"))
        self.actionIP_Recombine = QtGui.QAction(MainWindow)
        self.actionIP_Recombine.setObjectName(_fromUtf8("actionIP_Recombine"))
        self.actionFTP_Files_Monitoring = QtGui.QAction(MainWindow)
        self.actionFTP_Files_Monitoring.setObjectName(_fromUtf8("actionFTP_Files_Monitoring"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuSave.addSeparator()
        self.menuSave.addAction(self.actionSave_as_pcap)
        self.menuSave.addAction(self.actionSave_as_txt)
        self.menu6516.addAction(self.actionOpen)
        self.menu6516.addAction(self.menuSave.menuAction())
        self.menu6516.addSeparator()
        self.menu6516.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionChange_Interface)
        self.menuSniff.addAction(self.actionBegin)
        self.menuSniff.addAction(self.actionStop)
        self.menuSniff.addSeparator()
        self.menuSniff.addAction(self.actionClear_History)
        self.menuRecombine_2.addAction(self.actionIP_Recombine)
        self.menuRecombine_2.addAction(self.actionFTP_Files_Monitoring)
        self.menuFilter.addAction(self.actionFilter)
        self.menuFilter.addAction(self.actionSearch)
        self.menuFilter.addAction(self.menuRecombine_2.menuAction())
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menu6516.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuSniff.menuAction())
        self.menubar.addAction(self.menuFilter.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.PacketInfo.setCurrentIndex(0)
        QtCore.QObject.connect(self.PacketList, QtCore.SIGNAL(_fromUtf8("cellClicked(int,int)")), MainWindow.show_packet_details)
        QtCore.QObject.connect(self.pushButton_7, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.do_interface)
        QtCore.QObject.connect(self.StartButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.start_sniffing)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.save_txt)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.save_pcap)
        QtCore.QObject.connect(self.pushButton_3, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.open_pcap)
        QtCore.QObject.connect(self.pushButton_6, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.do_searcher)
        QtCore.QObject.connect(self.pushButton_5, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.do_filter)
        QtCore.QObject.connect(self.pushButton_4, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.clean)
        QtCore.QObject.connect(self.pushButton_8, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.recombine_ip)
        QtCore.QObject.connect(self.pushButton_10, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.File_reconstruct)
        QtCore.QObject.connect(self.StopButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.stop_sniffing)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "NetScope v1.0", None))
        item = self.PacketList.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Time", None))
        item = self.PacketList.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Source", None))
        item = self.PacketList.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Destination", None))
        item = self.PacketList.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Protocol", None))
        item = self.PacketList.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Information", None))
        self.PacketInfo.setTabText(self.PacketInfo.indexOf(self.Ethernet), _translate("MainWindow", "Ethernet", None))
        self.PacketInfo.setTabText(self.PacketInfo.indexOf(self.ip), _translate("MainWindow", "IP", None))
        self.PacketInfo.setTabText(self.PacketInfo.indexOf(self.more), _translate("MainWindow", "More...", None))
        self.label.setText(_translate("MainWindow", "Raw Data (hex):", None))
        self.label_2.setText(_translate("MainWindow", "Raw Data (string):", None))
        self.StartButton.setText(_translate("MainWindow", "Start", None))
        self.StopButton.setText(_translate("MainWindow", "Stop", None))
        self.pushButton_4.setText(_translate("MainWindow", "Clear", None))
        self.pushButton_7.setText(_translate("MainWindow", "Interface", None))
        self.pushButton_5.setText(_translate("MainWindow", "Filter", None))
        self.pushButton_6.setText(_translate("MainWindow", "Searcher", None))
        self.pushButton.setText(_translate("MainWindow", "Save", None))
        self.pushButton_2.setText(_translate("MainWindow", "Save TXT", None))
        self.pushButton_3.setText(_translate("MainWindow", "Open", None))
        self.pushButton_10.setText(_translate("MainWindow", "File", None))
        self.pushButton_8.setText(_translate("MainWindow", "Recombine", None))
        self.menu6516.setTitle(_translate("MainWindow", "Start", None))
        self.menuSave.setTitle(_translate("MainWindow", "Save", None))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit", None))
        self.menuSniff.setTitle(_translate("MainWindow", "Sniff", None))
        self.menuFilter.setTitle(_translate("MainWindow", "Operations", None))
        self.menuRecombine_2.setTitle(_translate("MainWindow", "Recombine", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionOpen.setText(_translate("MainWindow", "Open   ctrl+o", None))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.actionSave_as_pcap.setText(_translate("MainWindow", "Save as pcap", None))
        self.actionSave_as_txt.setText(_translate("MainWindow", "Save as txt", None))
        self.actionExit.setText(_translate("MainWindow", "Exit   ctrl+q", None))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionChange_Interface.setText(_translate("MainWindow", "Change Interface", None))
        self.actionBegin.setText(_translate("MainWindow", "Begin  F5", None))
        self.actionBegin.setShortcut(_translate("MainWindow", "F5", None))
        self.actionStop.setText(_translate("MainWindow", "Stop  F6", None))
        self.actionStop.setShortcut(_translate("MainWindow", "F6", None))
        self.actionClear.setText(_translate("MainWindow", "Clear", None))
        self.actionClear_History.setText(_translate("MainWindow", "Clear History", None))
        self.actionFilter.setText(_translate("MainWindow", "Filter", None))
        self.actionSearch.setText(_translate("MainWindow", "Search", None))
        self.actionIP_Recombine.setText(_translate("MainWindow", "IP Recombine", None))
        self.actionFTP_Files_Monitoring.setText(_translate("MainWindow", "FTP Files Monitoring", None))
        self.actionAbout.setText(_translate("MainWindow", "About...", None))

